const products = [
  {
    id: 1,
    name: 'Suporte Lanterna Empilhadeira Yale Hyster',
    category: 'empilhadeira',
    price: 370.00,
    oldPrice: null,
    icon: 'fa-lightbulb',
    badge: 'Destaque',
    rating: 5,
    reviews: 12
  },
  {
    id: 2,
    name: 'Bomba D\'Água Empilhadeira Motor PSI 2.4',
    category: 'empilhadeira',
    price: 600.00,
    oldPrice: null,
    icon: 'fa-water',
    badge: 'Novidade',
    rating: 5,
    reviews: 8
  },
  {
    id: 3,
    name: 'Rolamento 30207 Roda Empilhadeira Hyster Yale',
    category: 'empilhadeira',
    price: 68.00,
    oldPrice: null,
    icon: 'fa-cog',
    badge: null,
    rating: 4,
    reviews: 23
  },
  {
    id: 4,
    name: 'Bujão Empilhadeira Hyster Yale',
    category: 'empilhadeira',
    price: 25.00,
    oldPrice: null,
    icon: 'fa-plug',
    badge: null,
    rating: 4,
    reviews: 15
  },
  {
    id: 5,
    name: 'Conexão Redutor de Gás GLP Empilhadeira Hyster Yale',
    category: 'empilhadeira',
    price: 65.00,
    oldPrice: null,
    icon: 'fa-fire',
    badge: null,
    rating: 4,
    reviews: 9
  },
  {
    id: 6,
    name: 'Bucha Cilindro Inclinação Empilhadeira Hyster Yale',
    category: 'empilhadeira',
    price: 50.00,
    oldPrice: null,
    icon: 'fa-tools',
    badge: null,
    rating: 5,
    reviews: 11
  },
  {
    id: 7,
    name: 'Rolamento Capa Empilhadeira Hyster Yale',
    category: 'empilhadeira',
    price: 56.00,
    oldPrice: null,
    icon: 'fa-cog',
    badge: null,
    rating: 4,
    reviews: 17
  },
  {
    id: 8,
    name: 'Pino Cilindro Inclinação Empilhadeira Hyster Yale',
    category: 'empilhadeira',
    price: 129.99,
    oldPrice: 149.90,
    icon: 'fa-tools',
    badge: 'Oferta',
    rating: 5,
    reviews: 7
  },
  {
    id: 9,
    name: 'Polia da Mangueira Simples Empilhadeira Hyster Yale',
    category: 'empilhadeira',
    price: 60.00,
    oldPrice: null,
    icon: 'fa-cog',
    badge: null,
    rating: 4,
    reviews: 5
  },
  {
    id: 10,
    name: 'Rolamento 32011 Roda Empilhadeira Hyster Yale',
    category: 'empilhadeira',
    price: 119.90,
    oldPrice: null,
    icon: 'fa-cog',
    badge: null,
    rating: 5,
    reviews: 14
  },
  {
    id: 11,
    name: 'Rolamento Roda 32210 Empilhadeira Hyster Yale',
    category: 'empilhadeira',
    price: 119.90,
    oldPrice: null,
    icon: 'fa-cog',
    badge: null,
    rating: 4,
    reviews: 10
  },
  {
    id: 12,
    name: 'Bucha do Macal Torre Empilhadeira Hyster Yale',
    category: 'empilhadeira',
    price: 103.00,
    oldPrice: null,
    icon: 'fa-tools',
    badge: null,
    rating: 5,
    reviews: 6
  },
  {
    id: 13,
    name: 'Relé 24V Empilhadeira 17Ton Hyster Yale',
    category: 'empilhadeira',
    price: 100.00,
    oldPrice: null,
    icon: 'fa-bolt',
    badge: null,
    rating: 4,
    reviews: 19
  },
  {
    id: 14,
    name: 'Botão Mini Alavanca Sem Fio Empilhadeira Hyster Yale',
    category: 'empilhadeira',
    price: 245.90,
    oldPrice: null,
    icon: 'fa-gamepad',
    badge: 'Novidade',
    rating: 5,
    reviews: 4
  },
  {
    id: 15,
    name: 'Tampa Superior do Painel Empilhadeira Hyster Yale',
    category: 'empilhadeira',
    price: 350.00,
    oldPrice: null,
    icon: 'fa-border-all',
    badge: null,
    rating: 4,
    reviews: 8
  },
  {
    id: 16,
    name: 'Tampa Inferior do Painel Empilhadeira Hyster Yale',
    category: 'empilhadeira',
    price: 399.99,
    oldPrice: null,
    icon: 'fa-border-all',
    badge: null,
    rating: 4,
    reviews: 6
  },
  {
    id: 17,
    name: 'Chicote Elétrico Empilhadeira Hyster Yale',
    category: 'empilhadeira',
    price: 1450.00,
    oldPrice: null,
    icon: 'fa-project-diagram',
    badge: 'Premium',
    rating: 5,
    reviews: 3
  },
  {
    id: 18,
    name: 'Rolamento 62042 Empilhadeira Elétrica Hyster Yale',
    category: 'empilhadeira',
    price: 220.00,
    oldPrice: null,
    icon: 'fa-cog',
    badge: null,
    rating: 5,
    reviews: 7
  },
  {
    id: 19,
    name: 'Válvula de Alívio Empilhadeira Hyster Yale',
    category: 'empilhadeira',
    price: 1500.00,
    oldPrice: null,
    icon: 'fa-tachometer-alt',
    badge: 'Premium',
    rating: 5,
    reviews: 5
  },
  {
    id: 20,
    name: 'Pino Corrente Empilhadeira Hyster Yale',
    category: 'empilhadeira',
    price: 14.00,
    oldPrice: null,
    icon: 'fa-tools',
    badge: null,
    rating: 4,
    reviews: 21
  },
  {
    id: 21,
    name: 'Volante Mazda 2.2 com Cremalheira Empilhadeira Hyster Yale',
    category: 'empilhadeira',
    price: 2200.00,
    oldPrice: null,
    icon: 'fa-industry',
    badge: 'Destaque',
    rating: 5,
    reviews: 9
  },
  {
    id: 22,
    name: 'Par Lanterna Traseira Ford Ranger 2005-2009',
    category: 'iluminacao',
    price: 239.90,
    oldPrice: null,
    icon: 'fa-car',
    badge: 'Mais Vendido',
    rating: 5,
    reviews: 34
  },
  {
    id: 23,
    name: 'Lanterna Neblina Traseira Peugeot 207 2008-2014',
    category: 'iluminacao',
    price: 59.90,
    oldPrice: null,
    icon: 'fa-car',
    badge: null,
    rating: 4,
    reviews: 18
  },
  {
    id: 24,
    name: 'Lanterna Traseira Ford Ranger 2012-2022',
    category: 'iluminacao',
    price: 231.90,
    oldPrice: null,
    icon: 'fa-car',
    badge: null,
    rating: 5,
    reviews: 22
  },
  {
    id: 25,
    name: 'Par Lanterna Ecosport 2008-2012',
    category: 'iluminacao',
    price: 226.90,
    oldPrice: null,
    icon: 'fa-car',
    badge: null,
    rating: 4,
    reviews: 15
  },
  {
    id: 26,
    name: 'Par Lanterna Neblina Traseira Peugeot 207 2008-2015',
    category: 'iluminacao',
    price: 129.90,
    oldPrice: null,
    icon: 'fa-car',
    badge: 'Oferta',
    rating: 4,
    reviews: 12
  },
  {
    id: 27,
    name: 'Lanterna Traseira Fiat Strada 2020-2025',
    category: 'iluminacao',
    price: 235.90,
    oldPrice: null,
    icon: 'fa-car',
    badge: null,
    rating: 5,
    reviews: 8
  },
  {
    id: 28,
    name: 'Par Lanterna Traseira Ford Ranger 2009-2012',
    category: 'iluminacao',
    price: 426.90,
    oldPrice: null,
    icon: 'fa-car',
    badge: 'Premium',
    rating: 5,
    reviews: 11
  },
  {
    id: 29,
    name: 'Lanterna Ecosport 2008-2012 Acrílico Original',
    category: 'iluminacao',
    price: 119.90,
    oldPrice: null,
    icon: 'fa-car',
    badge: null,
    rating: 4,
    reviews: 27
  },
  {
    id: 30,
    name: 'Lanterna Traseira Prisma 2012-2016 Fumê',
    category: 'iluminacao',
    price: 219.90,
    oldPrice: null,
    icon: 'fa-car',
    badge: null,
    rating: 4,
    reviews: 19
  },
  {
    id: 31,
    name: 'Lanterna Traseira Amarok 2010-2014',
    category: 'iluminacao',
    price: 169.90,
    oldPrice: null,
    icon: 'fa-car',
    badge: null,
    rating: 5,
    reviews: 14
  },
  {
    id: 32,
    name: 'Par Lanterna Traseira S10 2008-2012 Original',
    category: 'iluminacao',
    price: 229.00,
    oldPrice: null,
    icon: 'fa-car',
    badge: 'Destaque',
    rating: 5,
    reviews: 31
  },
  {
    id: 33,
    name: 'Lanterna Traseira Peugeot 206 2005-2008',
    category: 'iluminacao',
    price: 179.90,
    oldPrice: null,
    icon: 'fa-car',
    badge: null,
    rating: 4,
    reviews: 16
  },
  {
    id: 34,
    name: 'Lanterna Traseira S10 2008-2012 Original (Unidade)',
    category: 'iluminacao',
    price: 119.00,
    oldPrice: null,
    icon: 'fa-car',
    badge: null,
    rating: 4,
    reviews: 23
  },
  {
    id: 35,
    name: 'Par Lanterna Traseira Hilux 2016-2021',
    category: 'iluminacao',
    price: 389.90,
    oldPrice: null,
    icon: 'fa-car',
    badge: 'Premium',
    rating: 5,
    reviews: 9
  },
  {
    id: 36,
    name: 'Farol Dianteiro Sandero Logan 2015-2019',
    category: 'iluminacao',
    price: 500.00,
    oldPrice: null,
    icon: 'fa-lightbulb',
    badge: null,
    rating: 5,
    reviews: 7
  }
];
